openapi: 3.0.1
info:
  title: mc-thumbnail-generator
  description: Service to generating thumbnails of layers.
  version: 1.1.2
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /screenshot:
    get:
      summary: Generates zip with thumbnails for downloading.
      parameters:
        - in: query
          name: productId
          schema:
            type: string
          description: Layer's product ID.
        - in: query
          name: productType
          schema:
            type: string
          description: The catalog type of the product.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/res'
        '500':
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    res:
      type: object
      properties:
        data:
          type: object
    error:
      type: object
      properties:
        error:
          type: string
