{{- $chartName := include "mc-thumbnail-generator.name" . -}}
{{- $tracingUrl := include "mc-thumbnail-generator.tracingUrl" . -}}
{{- $metricsUrl := include "mc-thumbnail-generator.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  THUMBNAIL_GENERATOR_ZIP_NAME: {{ quote .Values.env.thumbnailGenerator.zipName }}
  SERVICE_URL: {{ quote .Values.discreteClient.env.SERVICE_URL }}
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ quote .Values.globalClientApp.env.ACCESS_TOKEN_ATTRIBUTE_NAME }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ quote .Values.globalClientApp.env.ACCESS_TOKEN_INJECTION_TYPE }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ quote .Values.globalClientApp.env.ACCESS_TOKEN_TOKEN_VALUE }}
  DEFAULT_AOI_BBOX_POINTS: {{ quote .Values.thumbnailGenerator.defaultAOIBBoxPoints }}
  {{ end }}
{{- end }}
