{{- $chartName := include "mc-thumbnail-generator.name" . -}}
{{- $tracingUrl := include "mc-thumbnail-generator.tracingUrl" . -}}
{{- $metricsUrl := include "mc-thumbnail-generator.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ quote .Values.shared.accessToken.attributeName }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ quote .Values.shared.accessToken.injectionType }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ quote .Values.shared.accessToken.tokenValue }}
  CESIUM_CLIENT_WEB_CONFIG: {{ (tpl (.Files.Get "config/cesiumClientWebConfig.json") . ) | toJson}}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
    TELEMETRY_METRICS_ENABLED: 'true'
    TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  THUMBNAIL_GENERATOR_ZIP_NAME: {{ quote .Values.env.zipName }}
  SERVICE_URL: {{ quote .Values.env.serviceUrl }}
  DEFAULT_AOI_BBOX_POINTS: {{ quote .Values.env.defaultAOIBBoxPoints }}
  WATERMARK_TIMEOUT: {{ quote .Values.env.watermarkTimeout}}
  LOADING_TILES_TIMEOUT: {{ quote .Values.env.loadingTilesTimeout }}
{{- end }}
