{{- $MAIN_OBJECT_BLOCK := "configValues" -}}
{{- $COMPONENT_NAME := "backend" -}}
{{- $DATA := include "mcThumbnailGeneratorData" . -}}

{{- define "mcThumbnailGeneratorData" -}}
{{- $CONFIG_MANAGER_OBJECT := include "common.tplvalues.getGlobalObject" (dict "objName" "configManagment" "context" .) | fromYaml }}
{{- if not $CONFIG_MANAGER_OBJECT.enabled -}}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
{{- end }}
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ quote .Values.shared.accessToken.attributeName }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ quote .Values.shared.accessToken.injectionType }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ quote .Values.shared.accessToken.tokenValue }}
  CESIUM_CLIENT_WEB_CONFIG: {{ (tpl (.Files.Get "config/cesiumClientWebConfig.json") . ) | toJson}}
  THUMBNAIL_GENERATOR_ZIP_NAME: {{ quote .Values.env.zipName }}
  SERVICE_URL: {{ quote .Values.env.serviceUrl }}
  DEFAULT_AOI_BBOX_POINTS: {{ quote .Values.env.defaultAOIBBoxPoints }}
  WATERMARK_TIMEOUT: {{ quote .Values.env.watermarkTimeout}}
  LOADING_TILES_TIMEOUT: {{ quote .Values.env.loadingTilesTimeout }}
{{- end -}}

{{ include "mc-chart.configmap" (dict "MAIN_OBJECT_BLOCK" $MAIN_OBJECT_BLOCK "COMPONENT_NAME" $COMPONENT_NAME "DATA" $DATA "WITH_TELEMETRY_TRACING" false "WITH_TELEMETRY_METRICS" false "context" .)}}
