{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mc-thumbnail-generator.name" . -}}
{{- $cloudProviderDockerRegistryUrl := include "mc-thumbnail-generator.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "mc-thumbnail-generator.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "mc-thumbnail-generator.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "mc-thumbnail-generator.environment" . }}
    release: {{ $releaseName }}
    {{- include "mc-thumbnail-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}
      {{- include "mc-thumbnail-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}
        {{- include "mc-thumbnail-generator.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001050000
          volumeMounts:
            - name: cesium-client-root-config
              mountPath: /home/node/app/src/cesiumClientWeb/cesiumClientWebConfig.json
              subPath: cesiumClientWebConfig.json
              readOnly: true
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          # livenessProbe:
          #   initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          #   httpGet:
          #     path: /
          #     port: {{ .Values.env.targetPort }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      volumes:
        - name: cesium-client-root-config
          configMap:
            name: {{ .Release.Name }}-{{ $chartName }}-configmap
            items:
            - key: "CESIUM_CLIENT_WEB_CONFIG"
              path: "cesiumClientWebConfig.json"
{{- end -}}
