global:
  cloudProvider:
    dockerRegistryUrl: "localhost:5001"
    imagePullSecretName: 'my-registry-secret'
    flavor: openshift
  tracing: 
    url: ''
  metrics: 
    url: ''
  environment: ''
  clientApp:
    accessTokenAttributeName: 'token'
    accessTokenInjectionType: 'queryParam'
    accessTokenTokenValue: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZCI6WyJyYXN0ZXIiLCJkZW0iLCJ2ZWN0b3IiLCIzZCJdLCJpYXQiOjE1MTYyMzkwMjJ9.EnuWfcbCXkI8EEqdjcBb9SRSintpBZ6chLb6Odk_FzY'


enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
imagePullPolicy: "Always"

cloudProvider:
  dockerRegistryUrl: "localhost:5001"
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: mc-thumbnail-generator
  tag: 'v1.0.8'

env:
  port: 80
  targetPort: 3000
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: false
  path: /
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'

defaultAOIBBoxPoints: "[[33.64013671875,33.50475906922609],[37.957763671875,29.065772888415406]]"
serviceUrl: 'http://discrete-layer-client-int-bff-route-libot-integration.apps.v0h0bdx6.eastus.aroapp.io/graphql/graphql'
zipName: 'Thumbnails.zip'
watermarkTimeout: '90000'
