global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ''

shared:
  accessToken:
    attributeName: token
    injectionType: queryParam
    tokenValue: ''

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
imagePullPolicy: Always

cloudProvider:
  dockerRegistryUrl: localhost:5001
  imagePullSecretName: my-registry-secret
  flavor: openshift

image:
  repository: mc-thumbnail-generator
  tag: v1.0.21

env:
  port: 80
  targetPort: 3000
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  defaultAOIBBoxPoints: '[[33.64013671875,33.50475906922609],[37.957763671875,29.065772888415406]]'
  serviceUrl: http://bff.url
  zipName: Thumbnails.zip
  watermarkTimeout: 90000
  loadingTilesTimeout: 20000

resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 200Mi

route:
  enabled: true
  host:
  path: /
  tls: true
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 2m # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  type: nginx-kubernetes # supported values: 'nginx-org' | 'nginx-kubernetes'
  host:
  path: /
  cors:
    enabled: true
    origin: '*'
